# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yves' blog
tagline:          Not particularily focused
url:              http://yquemener.github.io
paginate:         8
baseurl:          /
author:
  name:           Yves Quemener
  url:            http://iv-devs.com
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/yquemener/yquemener.github.io
